version: '3.1'

services:
    php:
        build: docker/php
        container_name: metida_php
        volumes:
            - .:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini

    nginx:
        build: docker/nginx
        ports:
            - 1112:80
        volumes:
            - .:/var/www/html

    node:
        image: node:14
        working_dir: /app
        ports:
            - 3000:3000
        volumes:
            - .:/app

    mysql:
        image: mysql:8.0.28
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
